[colors.primary]
background = '#1a120d'
foreground = '#f0dfd7'
 
[colors.cursor]
text = '#f0dfd7'
cursor = '#d7c2b9' 
 
[colors.vi_mode_cursor]
text = '#1a120d'
cursor = '#ffb68e' 
 
[colors.search.matches]
foreground = '#52443c' 
background = '#cdc991' 
 
[colors.search.focused_match]
foreground = '#52443c' 
background = '#ffb68e' 
 
[colors.footer_bar]
foreground = '#52443c' 
background = '#f0dfd7' 
 
[colors.hints.start]
foreground = '#52443c' 
background = '#e6beaa' 
 
[colors.hints.end]
foreground = '#52443c' 
background = '#e6beaa' 
 
[colors.selection]
text = '#1a120d'
background = '#ffb68e'
 
 
[colors.normal]
black = '#181818' 
red = '#ffb4ab' 
green = '#ffb68e' 
yellow = '#8c4e28' 
blue = '#ffb68e' 
magenta = '#cdc991' 
cyan = '#e6beaa' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 
