[colors.primary]
background = '#1a1111'
foreground = '#f0dede'
 
[colors.cursor]
text = '#f0dede'
cursor = '#d7c1c1' 
 
[colors.vi_mode_cursor]
text = '#1a1111'
cursor = '#ffb3b4' 
 
[colors.search.matches]
foreground = '#524343' 
background = '#e6c18d' 
 
[colors.search.focused_match]
foreground = '#524343' 
background = '#ffb3b4' 
 
[colors.footer_bar]
foreground = '#524343' 
background = '#f0dede' 
 
[colors.hints.start]
foreground = '#524343' 
background = '#e6bdbd' 
 
[colors.hints.end]
foreground = '#524343' 
background = '#e6bdbd' 
 
[colors.selection]
text = '#1a1111'
background = '#ffb3b4'
 
 
[colors.normal]
black = '#181818' 
red = '#ffb4ab' 
green = '#ffb3b4' 
yellow = '#8f4a4d' 
blue = '#ffb3b4' 
magenta = '#e6c18d' 
cyan = '#e6bdbd' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 
