[colors.primary]
background = '#15130c'
foreground = '#e8e2d5'
 
[colors.cursor]
text = '#e8e2d5'
cursor = '#ccc6b5' 
 
[colors.vi_mode_cursor]
text = '#15130c'
cursor = '#d6c871' 
 
[colors.search.matches]
foreground = '#4a4739' 
background = '#a7d0b6' 
 
[colors.search.focused_match]
foreground = '#4a4739' 
background = '#d6c871' 
 
[colors.footer_bar]
foreground = '#4a4739' 
background = '#e8e2d5' 
 
[colors.hints.start]
foreground = '#4a4739' 
background = '#cfc7a2' 
 
[colors.hints.end]
foreground = '#4a4739' 
background = '#cfc7a2' 
 
[colors.selection]
text = '#15130c'
background = '#d6c871'
 
 
[colors.normal]
black = '#181818' 
red = '#ffb4ab' 
green = '#d6c871' 
yellow = '#695f11' 
blue = '#d6c871' 
magenta = '#a7d0b6' 
cyan = '#cfc7a2' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 
