[colors.primary]
background = '#1a1111'
foreground = '#f0dede'

[colors.selection]
text = '#f0dede'
background = '#733337'

[colors.cursor]
text = '#1a1111'
cursor = '#ffb3b4'

[colors.normal]
black   = '#1a1111'
red     = '#d06236'
green   = '#6ed68a'
yellow  = '#c9db7b'
blue    = '#d05d5d'
magenta = '#bf9192'
cyan    = '#ffb3b4'
white   = '#abb2bf'

[colors.bright]
black   = '#5c6370'
red     = '#e0845f'
green   = '#86e09e'
yellow  = '#d9e897'
blue    = '#ffbfc0'
magenta = '#bb5b6c'
cyan    = '#aa685f'
white   = '#ffffff'
